device:
  model: Philips Hue Dimmer Switch (RWL022)
  importUrl: https://raw.githubusercontent.com/dan-danache/hubitat/master/ikea-zigbee-drivers/Philips_RWL022.groovy
  image: https://dan-danache.github.io/hubitat/ikea-zigbee-drivers/img/Philips_RWL022.webp
  links:
  - name: device details
    url: https://dan-danache.github.io/hubitat/ikea-zigbee-drivers/#philips-hue-dimmer-switch-rwl022
  - name: community page
    url: https://community.hubitat.com/t/release-ikea-zigbee-drivers/123853

  fingerprints:
  - firmwares: 2.45.2_hF4400CA (100B-0119-02002D02)
    value: fingerprint profileId:'0104', endpointId:'01', inClusters:'0000,0001,0003,FC00,1000', outClusters:'0019,0000,0003,0004,0006,0008,0005,1000', model:'RWL022', manufacturer:'Signify Netherlands B.V.' 

  capabilities:
    - file: src/devices/Philips_RWL022/RWL022.groovy
    - file: src/capabilities/Battery.groovy
      params:
        half: true
    - file: src/capabilities/HealthCheck.groovy
      params:
        schedule: 0 0 0/1 ? * * *
        checkInterval: 3600  # every hour
        thereshold: 43200    # report device as offline if no message was received in the last 12 hours (device should report battery percentage every 5 hours)
    - file: src/capabilities/PowerSource.groovy
    - file: src/capabilities/HoldableButton.groovy
    - file: src/capabilities/PushableButton.groovy
      params:
        buttons:
        - { id: '01', name: 'Power', number: 1 }
        - { id: '02', name: '🔆',    number: 2 }
        - { id: '03', name: '🔅',    number: 3 }
        - { id: '04', name: 'Hue',   number: 4 }
    - file: src/capabilities/Refresh.groovy
      params:
        writeAttributes:
        - { cluster: '0x0000', attr: '0x0031', type: '0x19', value: '0x0B00', mfgCode: '0x100B', description: 'Philips magic attribute' }
    - file: src/capabilities/ReleasableButton.groovy
    - file: src/capabilities/ZigbeeBindings.groovy
      params:
        clusters: ['0x0006', '0x0008']
        groups: true
    - file: src/capabilities/FirmwareUpdate.groovy
