device:
  model: NodOn Multifunction Relay Switch (SIN-4-1-20)
  importUrl: https://raw.githubusercontent.com/dan-danache/hubitat/master/nodon-drivers/NodOn_SIN-4-1-20.groovy
  image: https://dan-danache.github.io/hubitat/nodon-drivers/img/NodOn_SIN-4-1-20.webp
  links:
  - name: device details
    url: https://dan-danache.github.io/hubitat/nodon-drivers/#nodon-multifunction-relay-switch-sin-4-1-20
  - name: community page
    url: https://community.hubitat.com/t/release-nodon-drivers/123853

  fingerprints:
  - firmwares: 3.0.0-1.4.4 (128B-000A-00000300)
    value: fingerprint profileId:'0104', endpointId:'01', inClusters:'0000,0003,0004,0005,0006,0007,1000,FC57', outClusters:'0003,0006,0019', model:'SIN-4-1-20', manufacturer:'NodOn', controllerType:'ZGB'

  capabilities:
    - name: RelaySwitch
    - file: src/capabilities/Switch.groovy
      params:
        powerOnBehavior: true
        onWithTimedOff: true
    - file: src/devices/NodOn_SIN-4-1-20/SIN-4-1-20.groovy
    - file: src/capabilities/HealthCheck.groovy
      params:
        schedule: 0 0 0/1 ? * * *
        checkInterval: 3600  # every hour
        thereshold: 3600     # report device as offline if no message was received in the last 60 minutes (device should report On/Off status every 10 minutes)
    - file: src/capabilities/PowerSource.groovy
    - file: src/capabilities/ZigbeeGroups.groovy
    - file: src/capabilities/FirmwareUpdate.groovy
