device:
  model: Philips Hue Wall Switch Module (RDM001)
  importUrl: https://raw.githubusercontent.com/dan-danache/hubitat/master/ikea-zigbee-drivers/Philips_RDM001.groovy
  image: https://dan-danache.github.io/hubitat/ikea-zigbee-drivers/img/Philips_RDM001.webp
  links:
  - name: device details
    url: https://dan-danache.github.io/hubitat/ikea-zigbee-drivers/#philips-hue-wall-switch-module-rdm001
  - name: community page
    url: https://community.hubitat.com/t/release-ikea-zigbee-drivers/123853

  fingerprints:
  - firmwares: 1.0.5 (100B-011C-0000041A)
    value: fingerprint profileId:'0104', endpointId:'01', inClusters:'0000,0001,0003,FC00', outClusters:'0003,0004,0006,0008,0019', model:'RDM001', manufacturer:'Signify Netherlands B.V.'

  capabilities:
    - file: src/devices/Philips_RDM001/RDM001.groovy
    - file: src/capabilities/Battery.groovy
    - file: src/capabilities/HealthCheck.groovy
      params:
        schedule: 0 0 0/1 ? * * *
        checkInterval: 3600  # every hour
        thereshold: 43200    # report device as offline if no message was received in the last 12 hours (device should report battery percentage every 5 hours)
    - file: src/capabilities/PowerSource.groovy
    - file: src/capabilities/HoldableButton.groovy
    - file: src/capabilities/PushableButton.groovy
      params:
        buttons:
        - { id: 'BUTTON_1', name: 'Left', number: 1 }
        - { id: 'BUTTON_2', name: 'Right', number: 2 }
    - file: src/capabilities/ReleasableButton.groovy
    - file: src/capabilities/ZigbeeBindings.groovy
      params:
        clusters: ['0x0006', '0x0008']
        groups: true
    - file: src/capabilities/FirmwareUpdate.groovy
