device:
  model: Swann One Key Fob (SWO-KEF1PA)
  importUrl: https://raw.githubusercontent.com/dan-danache/hubitat/master/ikea-zigbee-drivers/SWO-KEF1PA.groovy
  links:
  - https://dan-danache.github.io/hubitat/ikea-zigbee-drivers/
  - https://zigbee.blakadder.com/Swann_SWO-KEF1PA.html

  capabilities:
    - file: src/capabilities/IAS.groovy
    - file: src/capabilities/Battery.groovy
      params:
        half: true
    - file: src/capabilities/PushableButton.groovy
      params:
        buttons:
        - { id: 'PANIC', name: 'Panic', number: 1 }
        - { id: 'HOME',  name: 'Home',  number: 2 }
        - { id: 'AWAY',  name: 'Away',  number: 3 }
        - { id: 'NIGHT', name: 'Night', number: 4 }
    - file: src/capabilities/Refresh.groovy
      params:
        readAttributes:
        - { cluster: '0x0001', attr: '0x0021', description: 'BatteryPercentage' }
        - { cluster: '0x0500', attr: '0x0000', description: 'IAS ZoneState' }
        - { cluster: '0x0500', attr: '0x0001', description: 'IAS ZoneType' }
        - { cluster: '0x0500', attr: '0x0002', description: 'IAS ZoneStatus' }

zigbee:
  fingerprints:
  - firmwares: TBD
    value: fingerprint profileId:"0104", endpointId:"01", inClusters:"0000,0003,0001,0500,0000", outClusters:"0003,0501", model:"SWO-KEF1PA", manufacturer:"SwannONe"

  binds:
  - { endpoint: '0x01', cluster: '0x0501', reason: IAS Ancillary Control Equipment cluster }

  messages:
  - file: src/devices/SWO-KEF1PA/events.groovy
