device:
  model: IKEA Tradfri Remote Control (E1810)
  importUrl: https://raw.githubusercontent.com/dan-danache/hubitat/master/ikea-zigbee-drivers/Ikea_E1810.groovy
  image: https://dan-danache.github.io/hubitat/ikea-zigbee-drivers/img/Ikea_E1810.webp
  links:
  - name: device details
    url: https://dan-danache.github.io/hubitat/ikea-zigbee-drivers/#tradfri-remote-control-e1810
  - name: community page
    url: https://community.hubitat.com/t/release-ikea-zigbee-drivers/123853

  fingerprints:
  - firmwares: 24.4.5 (117C-11C1-24040005)
    value: fingerprint profileId:'0104', endpointId:'01', inClusters:'0000,0001,0003,0020,1000,FC57,FC7C', outClusters:'0003,0004,0005,0006,0008,0019,1000', model:'TRADFRI remote control', manufacturer:'IKEA of Sweden' 

  capabilities:
    - file: src/devices/Ikea_E1810/E1810.groovy
    - file: src/capabilities/Battery.groovy
      params:
        half: true
    - file: src/capabilities/HealthCheck.groovy
      params:
        schedule: 0 0 0/1 ? * * *
        checkInterval: 3600  # every hour
        thereshold: 43200    # report device as offline if no message was received in the last 12 hours (device should report battery percentage every 5 hours)
    - file: src/capabilities/HoldableButton.groovy
    - file: src/capabilities/PowerSource.groovy
    - file: src/capabilities/PushableButton.groovy
      params:
        buttons:
        - { id: 'POWER', name: 'Power', number: 1 }
        - { id: 'PLUS',  name: '🔆',   number: 2 }
        - { id: 'MINUS', name: '🔅',   number: 3 }
        - { id: 'NEXT',  name: 'Next',  number: 4 }
        - { id: 'PREV',  name: 'Prev',  number: 5 }
    - file: src/capabilities/ReleasableButton.groovy
    - file: src/capabilities/ZigbeeBindings.groovy
      params:
        clusters: ['0x0005', '0x0006', '0x0008']
    - file: src/capabilities/FirmwareUpdate.groovy
