device:
  model: IKEA Dimmable Light
  importUrl: https://raw.githubusercontent.com/dan-danache/hubitat/master/ikea-zigbee-drivers/Ikea_DIM-Light.groovy
  image: https://dan-danache.github.io/hubitat/ikea-zigbee-drivers/img/Ikea_DIM-Light.webp
  links:
  - name: device details
    url: https://dan-danache.github.io/hubitat/ikea-zigbee-drivers/#dimmable-light
  - name: community page
    url: https://community.hubitat.com/t/release-ikea-zigbee-drivers/123853

  fingerprints:
  - type: LED2103G5
    firmwares: 1.0.36 (117C-2100-01000036)
    value: fingerprint profileId:'0104', endpointId:'01', inClusters:'0000,0003,0004,0005,0006,0008,1000,FC7C', outClusters:'0019', model:'TRADFRI bulb E27 WW globe 806lm', manufacturer:'IKEA of Sweden'
  - type: LED2104R3
    firmwares: 1.0.36 (117C-2100-01000036)
    value: fingerprint profileId:'0104', endpointId:'01', inClusters:'0000,0003,0004,0005,0006,0008,1000,FC7C', outClusters:'0019', model:'TRADFRI bulb GU10 WW 345lm8', manufacturer:'IKEA of Sweden'
  - type: LED1623G12
    firmwares: 2.3.094 (117C-2101-23094631)
    value: fingerprint profileId:'0104', endpointId:'01', inClusters:'0000,0003,0004,0005,0006,0008,1000,FC7C', outClusters:'0005,0019,0020,1000', model:'TRADFRI bulb E27 opal 1000lm', manufacturer:'IKEA of Sweden'
  - type: LED1649C5E14EU
    firmwares: 2.3.094 (117C-2101-23094631)
    value: fingerprint profileId:'0104', endpointId:'01', inClusters:'0000,0003,0004,0005,0006,0008,1000,FC7C', outClusters:'0005,0019,0020,1000', model:'TRADFRI bulb E14 W op/ch 400lm', manufacturer:'IKEA of Sweden'
  - type: LED1934G3
    firmwares: 1.0.010 (117C-2102-00010010)
    value: fingerprint profileId:'0104', endpointId:'01', inClusters:'0000,0003,0004,0005,0006,0008,1000,FC57', outClusters:'0019', model:'TRADFRIbulbE27WWclear250lm', manufacturer:'IKEA of Sweden'
  - type: 10EU-IL-1
    firmwares: 1.2.245 (117C-4101-12245572)
    value: fingerprint profileId:'0104', endpointId:'01', inClusters:'0000,0003,0004,0005,0006,0008,0B05,1000', outClusters:'0005,0019,0020,1000', model:'TRADFRI Driver 10W', manufacturer:'IKEA of Sweden'
  - type: 10EU-IL-1
    firmwares: 2.3.086 (117C-4101-23086631)
    value: fingerprint profileId:'0104', endpointId:'01', inClusters:'0000,0003,0004,0005,0006,0008,1000,FC7C', outClusters:'0005,0019,0020,1000', model:'TRADFRI Driver 10W', manufacturer:'IKEA of Sweden'
  - type: LED1837R5
    firmwares: 2.3.093 (117C-4103-23093631)
    value: fingerprint profileId:'0104', endpointId:'01', inClusters:'0000,0003,0004,0005,0006,0008,1000,FC7C', outClusters:'0005,0019,0020,1000', model:'TRADFRI bulb GU10 WW 400lm', manufacturer:'IKEA of Sweden'
  - type: LED1842G3
    firmwares: 2.3.093 (117C-4103-23093631)
    value: fingerprint profileId:'0104', endpointId:'01', inClusters:'0000,0003,0004,0005,0006,0008,1000,FC7C', outClusters:'0005,0019,0020,1000', model:'TRADFRI bulb E27 WW clear 250lm', manufacturer:'IKEA of Sweden'
  - type: LED1836G9
    firmwares: 2.3.094 (117C-4103-23093631)
    value: fingerprint profileId:'0104', endpointId:'01', inClusters:'0000,0003,0004,0005,0006,0008,1000,FC7C', outClusters:'0005,0019,0020,1000', model:'TRADFRI bulb E27 WW 806lm', manufacturer:'IKEA of Sweden'
  - type: 30-IL44-1
    firmwares: 1.0.021 (117C-4104-00010021)
    value: fingerprint profileId:'0104', endpointId:'01', inClusters:'0000,0003,0004,0005,0006,0008,1000,FC57', outClusters:'0019', model:'SILVERGLANS IP44 LED driver', manufacturer:'IKEA of Sweden'
  - type: 30EU-IL-2
    firmwares: 1.0.002 (117C-4109-00010002)
    value: fingerprint profileId:'0104', endpointId:'01', inClusters:'0000,0003,0004,0005,0006,0008,1000,FC57', outClusters:'0019', model:'TRADFRI Driver 30W', manufacturer:'IKEA of Sweden'

  capabilities:
    - file: src/capabilities/Switch.groovy
      params:
        powerOnBehavior: true
        onWithTimedOff: true
    - file: src/capabilities/Brightness.groovy
    - file: src/capabilities/HealthCheck.groovy
      params:
        schedule: 0 0 0/1 ? * * *
        checkInterval: 3600  # every hour
        thereshold: 3600     # report device as offline if no message was received in the last 60 minutes (device should report On/Off status every 10 minutes)
    - file: src/capabilities/PowerSource.groovy
    - file: src/capabilities/ZigbeeGroups.groovy
    - file: src/capabilities/FirmwareUpdate.groovy
