device:
  model: IKEA Vindstyrka Air Quality Sensor (E2112)
  importUrl: https://raw.githubusercontent.com/dan-danache/hubitat/master/ikea-zigbee-drivers/Ikea_E2112.groovy
  image: https://dan-danache.github.io/hubitat/ikea-zigbee-drivers/img/Ikea_E2112.webp
  links:
  - name: device details
    url: https://dan-danache.github.io/hubitat/ikea-zigbee-drivers/#vindstyrka-air-quality-sensor-e2112
  - name: community page
    url: https://community.hubitat.com/t/release-ikea-zigbee-drivers/123853

  fingerprints:
  - firmwares: 1.0.010 (117C-110F-00010010)
    value: fingerprint profileId:'0104', endpointId:'01', inClusters:'0000,0003,0004,0402,0405,FC57,FC7C,042A,FC7E', outClusters:'0003,0019,0020,0202', model:'VINDSTYRKA', manufacturer:'IKEA of Sweden' 

  capabilities:
    - name: Sensor
    - file: src/devices/Ikea_E2112/FineParticulateMatter.groovy
    - file: src/devices/Ikea_E2112/VocIndex.groovy
    - file: src/capabilities/Temperature.groovy
    - file: src/capabilities/RelativeHumidity.groovy
    - file: src/capabilities/HealthCheck.groovy
      params:
        schedule: 0 0 0/1 ? * * *
        checkInterval: 3600  # every hour
        thereshold: 3600     # report device as offline if no message was received in the last 60 minutes (device should report On/Off status every 10 minutes)
    - file: src/capabilities/PowerSource.groovy
    - file: src/capabilities/FirmwareUpdate.groovy
