device:
  model: IKEA Tradfri Control Outlet
  zigbeeId: TRADFRI control outlet
  type: E1603

  capabilities:
    HealthCheck:
      schedule: 0 0 0/1 ? * * *
      checkInterval: 3600  # every hour
      thereshold: 3600     # report device as offline if no message was received in the last 60 minutes (device should report On/Off status every 5 to 10 minutes)
    PowerSource:
      mains: true
    Outlet: true
    Refresh: true
    ZigbeeRouter: true

zigbee:
  fingerprints:
  - firmwares: 2.0.024
    value: fingerprint profileId:"0104", endpointId:"01", inClusters:"0000,0003,0004,0005,0006,0008,1000,FC7C", outClusters:"0005,0019,0020,1000", model:"TRADFRI control outlet", manufacturer:"IKEA of Sweden"

  - firmwares: 2.3.089
    value: fingerprint profileId:"0104", endpointId:"01", inClusters:"0000,0003,0004,0005,0006,0008,1000,FC7C", outClusters:"0019,0020,1000", model:"TRADFRI control outlet", manufacturer:"IKEA of Sweden"

  reporting:
  - { cluster: '0x0006', attribute: '0x0000', type: '0x10', min: 300, max: 600, delta: '0x00', reason: 'Report On/Off status every 5 to 10 minutes' }

  messages:
    handle:
    - file: src/devices/E1603/events.groovy

    ignore:
    - cluster: '0x0001'
      command: '0x07'
      name: Configure Reporting Response

    - cluster: '0x0003'
      command: '0x01'
      name: Identify Query Response

    - cluster: '0x0006'
      command: '0x07'
      name: Reporting Configuration Response

    # We get this entry in the log when the "Configure" button is clicked
    # Payload data is [03, FD, FF, 04, 01, 01, 19, 00, 00]
    - cluster: '0x0006'
      command: '0x00'
      name: Unknown Zigbee Response with weird payload

    - cluster: '0x8034'
      name: Leave Response
