device:
  model: IKEA Tradfri Control Outlet
  type: E1603

  capabilities:
    - file: src/capabilities/Switch.groovy
      params:
        powerOnBehavior: true
        onWithTimedOff: true
    - file: src/capabilities/HealthCheck.groovy
      params:
        schedule: 0 0 0/1 ? * * *
        checkInterval: 3600  # every hour
        thereshold: 3600     # report device as offline if no message was received in the last 60 minutes (device should report On/Off status at least every 10 minutes)
    - file: src/capabilities/PowerSource.groovy
    - file: src/capabilities/Refresh.groovy
      params:
        readAttributes:
        - { cluster: '0x0006', attr: '0x0000', description: 'OnOff := { 0x00:Off, 0x01:On }' }
        - { cluster: '0x0006', attr: '0x4003', description: 'PowerOnBehavior := { 0x00:TurnPowerOff, 0x01:TurnPowerOn, 0xFF:RestorePreviousState }' }
    - file: src/capabilities/ZigbeeRouter.groovy
    - file: src/capabilities/FirmwareUpdate.groovy

zigbee:
  fingerprints:
  - firmwares: 2.0.024
    value: fingerprint profileId:"0104", endpointId:"01", inClusters:"0000,0003,0004,0005,0006,0008,1000,FC7C", outClusters:"0005,0019,0020,1000", model:"TRADFRI control outlet", manufacturer:"IKEA of Sweden"

  - firmwares: 2.3.089
    value: fingerprint profileId:"0104", endpointId:"01", inClusters:"0000,0003,0004,0005,0006,0008,1000,FC7C", outClusters:"0019,0020,1000", model:"TRADFRI control outlet", manufacturer:"IKEA of Sweden"

  messages:
  - file: src/devices/E1603/events.groovy
