device:
  model: IKEA Vallhorn Motion Sensor (E2134)
  importUrl: https://raw.githubusercontent.com/dan-danache/hubitat/master/ikea-zigbee-drivers/Ikea_E2134.groovy
  image: https://dan-danache.github.io/hubitat/ikea-zigbee-drivers/img/Ikea_E2134.webp
  links:
  - name: device details
    url: https://dan-danache.github.io/hubitat/ikea-zigbee-drivers/#vallhorn-motion-sensor-e2134
  - name: community page
    url: https://community.hubitat.com/t/release-ikea-zigbee-drivers/123853

  fingerprints:
  - firmwares: 1.0.57 (117C-1938-01000057)
    value: fingerprint profileId:'0104', endpointId:'01', inClusters:'0000,0001,0003,0020,0B05,1000,FC7C,FC81', outClusters:'0003,0004,0006,0019,1000', model:'VALLHORN Wireless Motion Sensor', manufacturer:'IKEA of Sweden'

  capabilities:
    - name: Sensor
    - name: MotionSensor
    - name: IlluminanceMeasurement
    - file: src/devices/Ikea_E2134/E2134.groovy
    - file: src/capabilities/Battery.groovy
    - file: src/capabilities/HealthCheck.groovy
      params:
        schedule: 0 0 0/1 ? * * *
        checkInterval: 3600  # every hour
        thereshold: 43200    # report device as offline if no message was received in the last 12 hours (device should report battery percentage every 5 hours)
    - file: src/capabilities/PowerSource.groovy
    - file: src/capabilities/Refresh.groovy
      params:
        readBindings: true
        readAttributes:
        - { endpoint: '0x02', cluster: '0x0406', attr: '0x0000', description: 'Occupancy' }
        - { endpoint: '0x03', cluster: '0x0400', attr: '0x0000', description: 'Illuminance' }
    - file: src/capabilities/ZigbeeBindings.groovy
      params:
        clusters: ['0x0006']
        groups: true
    - file: src/capabilities/FirmwareUpdate.groovy
