device:
  model: IKEA Starkvind Air Purifier (E2006)
  importUrl: https://raw.githubusercontent.com/dan-danache/hubitat/master/ikea-zigbee-drivers/E2006.groovy
  links:
  - https://dan-danache.github.io/hubitat/ikea-zigbee-drivers/
  - https://zigbee.blakadder.com/Ikea_E1603.html
  - https://ww8.ikea.com/ikeahomesmart/releasenotes/releasenotes.html
  - https://static.homesmart.ikea.com/releaseNotes/

  capabilities:
    - file: src/devices/E2006/AirPurifier.groovy
    - file: src/capabilities/HealthCheck.groovy
      params:
        schedule: 0 0 0/1 ? * * *
        checkInterval: 3600  # every hour
        thereshold: 3600     # report device as offline if no message was received in the last 60 minutes (device should report attributes every 10 minutes)
    - file: src/capabilities/PowerSource.groovy
    - file: src/capabilities/Refresh.groovy
      params:
        readAttributes:
        - { cluster: '0xFC7D', attr: '0x0000', mfgCode: '0x117C', description: 'FilterRunTime' }
        - { cluster: '0xFC7D', attr: '0x0001', mfgCode: '0x117C', description: 'ReplaceFilter' }
        - { cluster: '0xFC7D', attr: '0x0002', mfgCode: '0x117C', description: 'FilterLifeTime' }
        - { cluster: '0xFC7D', attr: '0x0003', mfgCode: '0x117C', description: 'DisablePanelLights' }
        - { cluster: '0xFC7D', attr: '0x0004', mfgCode: '0x117C', description: 'PM25Measurement' }
        - { cluster: '0xFC7D', attr: '0x0005', mfgCode: '0x117C', description: 'ChildLock' }
        - { cluster: '0xFC7D', attr: '0x0006', mfgCode: '0x117C', description: 'FanMode' }
    - file: src/capabilities/ZigbeeRouter.groovy
    - file: src/capabilities/FirmwareUpdate.groovy

zigbee:
  fingerprints:
  - firmwares: 1.0.033 (117C-110C-00010033)
    value: fingerprint profileId:"0104", endpointId:"01", inClusters:"0000,0003,0004,0005,0202,FC57,FC7D", outClusters:"0019,0400,042A", model:"STARKVIND Air purifier table", manufacturer:"IKEA of Sweden"

  - firmwares: 1.1.001 (117C-110C-00011001)
    value: fingerprint profileId:"0104", endpointId:"01", inClusters:"0000,0003,0004,0005,0202,FC57,FC7C,FC7D", outClusters:"0019,0400,042A", model:"STARKVIND Air purifier table", manufacturer:"IKEA of Sweden"
