device:
  model: IKEA Styrbar Remote Control N2 (E2002)
  importUrl: https://raw.githubusercontent.com/dan-danache/hubitat/master/ikea-zigbee-drivers/E2002.groovy
  links:
  - https://dan-danache.github.io/hubitat/ikea-zigbee-drivers/
  - https://zigbee.blakadder.com/Ikea_E2002.html
  - https://ww8.ikea.com/ikeahomesmart/releasenotes/releasenotes.html
  - https://static.homesmart.ikea.com/releaseNotes/

  capabilities:
    - file: src/capabilities/Battery.groovy
      params:
        half: true
    - file: src/capabilities/HealthCheck.groovy
      params:
        schedule: 0 0 0/1 ? * * *
        checkInterval: 3600  # every hour
        thereshold: 43200    # report device as offline if no message was received in the last 12 hours (device should report battery percentage every 5 hours)
    - file: src/capabilities/HoldableButton.groovy
    - file: src/capabilities/PowerSource.groovy
    - file: src/capabilities/PushableButton.groovy
      params:
        buttons:
        - { id: 'PLUS',  name: '🔆',   number: 1 }
        - { id: 'MINUS', name: '🔅',   number: 2 }
        - { id: 'NEXT',  name: 'Next',  number: 3 }
        - { id: 'PREV',  name: 'Prev',  number: 4 }
    - file: src/capabilities/Refresh.groovy
      params:
        readAttributes:
        - { cluster: '0x0001', attr: '0x0021', description: 'BatteryPercentage' }
    - file: src/capabilities/ReleasableButton.groovy
    - file: src/capabilities/FirmwareUpdate.groovy

zigbee:
  fingerprints:
  - firmwares: 1.0.024
    value: fingerprint profileId:"0104", endpointId:"01", inClusters:"0000,0001,0003,0020,1000,FC57", outClusters:"0003,0006,0008,0019,1000", model:"Remote Control N2", manufacturer:"IKEA of Sweden"

  - firmwares: 2.4.5 (117C-11CB-02040005)
    value: fingerprint profileId:"0104", endpointId:"01", inClusters:"0000,0001,0003,0020,1000,FC57,FC7C", outClusters:"0003,0005,0006,0008,0019,1000", model:"Remote Control N2", manufacturer:"IKEA of Sweden"

  binds:
  - { endpoint: '0x01', cluster: '0x0005', reason: Scenes cluster }
  - { endpoint: '0x01', cluster: '0x0006', reason: On/Off cluster }
  - { endpoint: '0x01', cluster: '0x0008', reason: Level Control cluster }

  messages:
  - file: src/devices/E2002/events.groovy
