device:
  model: IKEA Styrbar Remote Control N2
  type: E2002

  capabilities:
    - file: src/capabilities/Battery.groovy
      params:
        half: true
    - file: src/capabilities/HealthCheck.groovy
      params:
        schedule: 0 0 0/1 ? * * *
        checkInterval: 3600  # every hour
        thereshold: 43200    # report device as offline if no message was received in the last 12 hours (device should report battery percentage at least every 12 hours)
    - file: src/capabilities/HoldableButton.groovy
    - file: src/capabilities/PowerSource.groovy
    - file: src/capabilities/PushableButton.groovy
      params:
        buttons:
        - { id: 'PLUS',  name: '🔆',   number: 1 }
        - { id: 'MINUS', name: '🔅',   number: 2 }
        - { id: 'NEXT',  name: 'Next',  number: 3 }
        - { id: 'PREV',  name: 'Prev',  number: 4 }
    - file: src/capabilities/ReleasableButton.groovy

zigbee:
  fingerprints:
  - firmwares: 1.0.024
    value: fingerprint profileId:"0104", endpointId:"01", inClusters:"0000,0001,0003,0020,1000,FC57", outClusters:"0003,0006,0008,0019,1000", model:"Remote Control N2", manufacturer:"IKEA of Sweden"

  - firmwares: 2.4.5
    value: fingerprint profileId:"0104", endpointId:"01", inClusters:"0000,0001,0003,0020,1000,FC57,FC7C", outClusters:"0003,0005,0006,0008,0019,1000", model:"Remote Control N2", manufacturer:"IKEA of Sweden"

  binds:
  - { endpoint: '0x01', cluster: '0x0005', reason: Scenes cluster }
  - { endpoint: '0x01', cluster: '0x0006', reason: On/Off cluster }
  - { endpoint: '0x01', cluster: '0x0008', reason: Level Control cluster }

  messages:
  - file: src/devices/E2002/events.groovy
