device:
  model: Aqara Dual Relay Module T2 (DCM-K01)
  importUrl: https://raw.githubusercontent.com/dan-danache/hubitat/master/ikea-zigbee-drivers/DCM-K01.groovy
  links:
  - https://dan-danache.github.io/hubitat/ikea-zigbee-drivers/
  - https://zigbee.blakadder.com/Aqara_LLKZMK12LM.html

  capabilities:
    - file: src/devices/DCM-K01/DCM-K01.groovy
    - file: src/capabilities/PowerMeter.groovy
    - file: src/capabilities/MultiRelay.groovy
    - file: src/capabilities/PushableButton.groovy
      params:
        buttons:
        - { id: 'S1', name: 'S1', number: 1 }
        - { id: 'S2', name: 'S2', number: 2 }
    - file: src/capabilities/Refresh.groovy
      params:
        readAttributes:
        - { endpoint: '0x01', cluster: '0x0006', attr: '0x0000', description: 'OnOff - Switch 1' }
        - { endpoint: '0x02', cluster: '0x0006', attr: '0x0000', description: 'OnOff - Switch 2' }

        - { endpoint: '0x01', cluster: '0x0B04', attr: '0x0604', description: 'PowerMultiplier' }
        - { endpoint: '0x01', cluster: '0x0B04', attr: '0x0605', description: 'PowerDivisor' }
        - { endpoint: '0x01', cluster: '0x0B04', attr: '0x050B', description: 'ActivePower' }

        - { endpoint: '0x01', cluster: '0x0702', attr: '0x0301', description: 'EnergyMultiplier' }
        - { endpoint: '0x01', cluster: '0x0702', attr: '0x0302', description: 'EnergyDivisor' }
        - { endpoint: '0x01', cluster: '0x0702', attr: '0x0000', description: 'EnergySumation' }

        - { endpoint: '0x01', cluster: '0xFCC0', attr: '0x00F7', mfgCode: '0x115F', description: 'LumiSpecific' }
    - file: src/capabilities/ZigbeeRouter.groovy
    - file: src/capabilities/FirmwareUpdate.groovy

zigbee:
  fingerprints:
  - firmwares: Unknown
    value: fingerprint profileId:"0104", endpointId:"01", inClusters:"0B04,0702,0005,0004,0003,0012,0000,0006,FCC0", outClusters:"0019,000A", model:"lumi.switch.acn047", manufacturer:"Aqara"
