#
# IMPORTANT: Still waiting for a firmware upgrade for this device as it still uses group bindings and Hubitat does not support this behavior
#
device:
  model: IKEA Tradfri Motion Sensor
  zigbeeId: TRADFRI motion sensor
  type: E1745
  capabilities:
    Battery: true
    HealthCheck:
      schedule: 0 0 0/1 ? * * *
      checkInterval: 3600  # every hour
      thereshold: 43200    # report device as offline if no message was received in the last 12 hours (device should report battery level every 6 to 12 hours)
    MotionSensor: true
    PowerSource:
      battery: true

zigbee:
  fingerprints:
  - firmwares: 2.0.022
    value: fingerprint profileId:"0104", endpointId:"01", inClusters:"0000,0001,0003,0009,0020,1000,FC7C", outClusters:"0003,0004,0006,0008,0019,1000", model:"TRADFRI motion sensor", manufacturer:"IKEA of Sweden"

  binds:
  - { endpoint: '0x01', cluster: '0x0006', reason: General - On/Off cluster }

  reporting:
  - { cluster: '0x0001', attribute: '0x0021', type: 'DataType.UINT8', min: 21600, max: 43200, delta: '0x00', reason: 'Report battery level every 6 to 12 hours' }

  messages:
    handle:
    - file: src/devices/E1745/events.groovy
    - file: src/events/battery-percentage.groovy

    ignore:
    - cluster: '0x0001'
      command: '0x07'
      name: Configure Reporting Response

    - cluster: '0x0003'
      command: '0x01'
      name: Identify Query Response

    - cluster: '0x8034'
      name: Leave Response
