device:
  model: IKEA Tradfri Motion Sensor (E1745)
  importUrl: https://raw.githubusercontent.com/dan-danache/hubitat/master/ikea-zigbee-drivers/E1745.groovy
  links:
  - https://dan-danache.github.io/hubitat/ikea-zigbee-drivers/
  - https://zigbee.blakadder.com/Ikea_E1745.html
  - https://ww8.ikea.com/ikeahomesmart/releasenotes/releasenotes.html
  - https://static.homesmart.ikea.com/releaseNotes/

  capabilities:
    - file: src/capabilities/MotionSensor.groovy
    - file: src/capabilities/Battery.groovy
      params:
        half: true
    - file: src/capabilities/HealthCheck.groovy
      params:
        schedule: 0 0 0/1 ? * * *
        checkInterval: 3600  # every hour
        thereshold: 43200    # report device as offline if no message was received in the last 12 hours (device should report battery percentage at least every 12 hours)
    - file: src/capabilities/PowerSource.groovy
    - file: src/capabilities/Refresh.groovy
      params:
        readAttributes:
        - { cluster: '0x0001', attr: '0x0021', description: 'BatteryPercentage' }
    - file: src/capabilities/FirmwareUpdate.groovy

zigbee:
  fingerprints:
  - firmwares: 24.4.5 (117C-11C8-24040005)
    value: fingerprint profileId:"0104", endpointId:"01", inClusters:"0000,0001,0003,0020,1000,FC57,FC7C", outClusters:"0003,0004,0006,0008,0019,1000", model:"TRADFRI motion sensor", manufacturer:"IKEA of Sweden"

  binds:
  - { endpoint: '0x01', cluster: '0x0006', reason: On/Off cluster }

  messages:
  - file: src/devices/E1745/events.groovy
