device:
  model: IKEA Somrig Shortcut Button (E2213)
  importUrl: https://raw.githubusercontent.com/dan-danache/hubitat/master/ikea-zigbee-drivers/E2213.groovy
  links:
  - https://dan-danache.github.io/hubitat/ikea-zigbee-drivers/
  - https://zigbee.blakadder.com/Ikea_E2213.html
  - https://ww8.ikea.com/ikeahomesmart/releasenotes/releasenotes.html
  - https://static.homesmart.ikea.com/releaseNotes/

  capabilities:
    - file: src/capabilities/Battery.groovy
      params:
        half: true
    - file: src/capabilities/DoubleTapableButton.groovy
    - file: src/capabilities/HealthCheck.groovy
      params:
        schedule: 0 0 0/1 ? * * *
        checkInterval: 3600  # every hour
        thereshold: 43200    # report device as offline if no message was received in the last 12 hours (device should report battery percentage every 5 hours)
    - file: src/capabilities/HoldableButton.groovy
    - file: src/capabilities/PowerSource.groovy
    - file: src/capabilities/PushableButton.groovy
      params:
        buttons:
        - { id: 'DOT_1', name: '•',  number: 1 }
        - { id: 'DOT_2', name: '••', number: 2 }
    - file: src/capabilities/Refresh.groovy
      params:
        readAttributes:
        - { cluster: '0x0001', attr: '0x0021', description: 'BatteryPercentage' }
    - file: src/capabilities/ReleasableButton.groovy
    - file: src/capabilities/FirmwareUpdate.groovy

zigbee:
  fingerprints:
  - firmwares: 1.0.20 (117C-3B08-01000020)
    value: fingerprint profileId:"0104", endpointId:"01", inClusters:"0000,0001,0003,0004,0020,1000,FC7C,0xFC80", outClusters:"0003,0004,0006,0008,0019,1000,0xFC80", model:"SOMRIG shortcut button", manufacturer:"IKEA of Sweden"

  binds:
  - { endpoint: '0x01', cluster: '0xFC80', mfgCode: '0x117C', reason: IKEA Button cluster (ep 01) }
  - { endpoint: '0x02', cluster: '0xFC80', mfgCode: '0x117C', reason: IKEA Button cluster (ep 02) }

  messages:
  - file: src/devices/E2213/events.groovy
