device:
  model: IKEA White Spectrum Light
  importUrl: https://raw.githubusercontent.com/dan-danache/hubitat/master/ikea-zigbee-drivers/Ikea_WS-Light.groovy
  image: https://dan-danache.github.io/hubitat/ikea-zigbee-drivers/img/Ikea_WS-Light.webp
  links:
  - name: device details
    url: https://dan-danache.github.io/hubitat/ikea-zigbee-drivers/#ws-light
  - name: community page
    url: https://community.hubitat.com/t/release-ikea-zigbee-drivers/123853

  fingerprints:
  - type: LED2101G4
    firmwares: 1.1.003 (117C-2204-00011003)
    value: fingerprint profileId:'0104', endpointId:'01', inClusters:'0000,0003,0004,0005,0006,0008,0300,1000,FC57', outClusters:'0019', model:'TRADFRI bulb E14 WS globe 470lm', manufacturer:'IKEA of Sweden'
  - type: LED1949C5
    firmwares: 1.1.003 (117C-2204-00011003)
    value: fingerprint profileId:'0104', endpointId:'01', inClusters:'0000,0003,0004,0005,0006,0008,0300,1000,FC57', outClusters:'0019', model:'TRADFRIbulbE14WScandleopal470lm', manufacturer:'IKEA of Sweden'
  - type: LED2201G8
    firmwares: 3.0.10 (117C-2206-03000010)
    value: fingerprint profileId:'0104', endpointId:'01', inClusters:'0000,0003,0004,0005,0006,0008,0300,1000,FC7C', outClusters:'0019', model:'TRADFRI bulb E27 WS globe 1055lm', manufacturer:'IKEA of Sweden'

  capabilities:
    - file: src/capabilities/Switch.groovy
      params:
        powerOnBehavior: true
        onWithTimedOff: true
    - file: src/capabilities/ColorTemperature.groovy
    - file: src/capabilities/Brightness.groovy
    - file: src/capabilities/HealthCheck.groovy
      params:
        schedule: 0 0 0/1 ? * * *
        checkInterval: 3600  # every hour
        thereshold: 3600     # report device as offline if no message was received in the last 60 minutes (device should report On/Off status every 10 minutes)
    - file: src/capabilities/PowerSource.groovy
    - file: src/capabilities/ZigbeeGroups.groovy
    - file: src/capabilities/FirmwareUpdate.groovy
