device:
  model: IKEA Badring Water Leakage Sensor (E2202)
  importUrl: https://raw.githubusercontent.com/dan-danache/hubitat/master/ikea-zigbee-drivers/E2202.groovy
  links:
  - https://dan-danache.github.io/hubitat/ikea-zigbee-drivers/
  - https://zigbee.blakadder.com/Ikea_E2202.html
  - https://ww8.ikea.com/ikeahomesmart/releasenotes/releasenotes.html
  - https://static.homesmart.ikea.com/releaseNotes/

  capabilities:
    - name: WaterSensor
    - name: Sensor
    - file: src/capabilities/IAS.groovy
    - file: src/capabilities/Battery.groovy
      params:
        half: true
    - file: src/capabilities/HealthCheck.groovy
      params:
        schedule: 0 0 0/1 ? * * *
        checkInterval: 3600  # every hour
        thereshold: 43200    # report device as offline if no message was received in the last 12 hours (device should report battery percentage every 5 hours)
    - file: src/capabilities/PowerSource.groovy
    - file: src/capabilities/Refresh.groovy
      params:
        readAttributes:
        - { cluster: '0x0001', attr: '0x0021', description: 'BatteryPercentage' }
        - { cluster: '0x0500', attr: '0x0000', description: 'IAS ZoneState' }
        - { cluster: '0x0500', attr: '0x0001', description: 'IAS ZoneType' }
        - { cluster: '0x0500', attr: '0x0002', description: 'IAS ZoneStatus' }
    - file: src/capabilities/FirmwareUpdate.groovy

zigbee:
  fingerprints:
  - firmwares: 1.0.7 (117C-24D4-01000007)
    value: fingerprint profileId:"0104", endpointId:"01", inClusters:"0000,0001,0003,0020,0500,0B05,FC7C,FC81", outClusters:"0003,0004,0019", model:"BADRING Water Leakage Sensor", manufacturer:"IKEA of Sweden"

  messages:
  - file: src/devices/E2202/events.groovy
